### ISSUE TITLE
500's are not caught by new 404 page

### ISSUE THREAD

**Issue by sursh** [sursh/blaggregator#77]
This is a good test case (hah) for tests. Found a small bug in the pull request I just merged, after deploying: 

http://www.blaggregator.us/post/e9VGgd/view
throws the standard 500 (I expected it to throw the pretty 404)

http://www.blaggregator.us/post/e9VnthoeunthGgd/view
throws a pretty 404 (as expected)

**Comment by punchagan** [comment]
I don't see a 500 on the first url you mention. So, I don't exactly understand what the bug is.

**Comment by sursh** [comment]
What do you see?

On Mon, Mar 9, 2015 at 3:55 PM, Puneeth Chaganti <notifications@github.com>
wrote:

> I don't see a 500 on the first url you mention. So, I don't exactly
> understand what the bug is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sursh/blaggregator/issues/77#issuecomment-77929071>.
>



-- 
-Sasha

**Comment by sursh** [comment]
uhhhh that link works for me now. maybe a fluke of deploying? let's close this and deal with it if it comes back.

**Comment by punchagan** [comment]
That sounds reasonable. :+1:
